# GitHub Sponsors (if you have it enabled)
# github: LuisGamas

# Buy Me A Coffee
buymeacoffee: luisgamas

# PayPal (using custom URL for donation button with hosted_button_id)
custom:
  - "https://www.paypal.com/donate/?hosted_button_id=NYCR5M6QHZ7JC"
